### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by faeller**

### CODE REVIEW

**Comment by faeller** [comment]
@hagenest 

I don't want to rush you, but please do understand that I want you to be rushed, ty

kthxbye

**Comment by faeller** [comment]
@hagenest

**Comment by faeller** [comment]
@hagenest

**Comment by faeller** [comment]
@hagenest

**Comment by faeller** [comment]
@hagenest

**Comment by hagenest** [comment]
Alright, fixed it myself.

**Pull request merged**
